### ISSUE TITLE
The Observer ParameterLoader doesn't load objects in Vr4

### ISSUE THREAD

**Issue by raphait** [caelum/vraptor-jpa#26]
In fact, the ParameterLoader never loads an entity. It's because missing annotations `@RequestScoped` and `@Inject` as @garcia-jj said in thread (https://groups.google.com/d/msg/caelum-vraptor/t7mcjq80Q6E/7kL9FJN0uj8J) , I'd already tested and this is the problem.

**Comment by rafaelGuerreiro** [comment]
Guys, this commit isn't published on maven.
The most actual version is 4.0.2 and it doesn't include this commit.

**Comment by Turini** [comment]
@rafaelGuerreiro thank you for let us know. 
I'll release a new version with the latest changes today.

**Comment by Turini** [comment]
Done. It'll be available in a few hours on maven repository

**Comment by rafaelGuerreiro** [comment]
Can you push the code to the branch VRaptor4Version? (If you already did, I'm sorry, I didn't find the commit.)

**Comment by Turini** [comment]
The [commit](https://github.com/caelum/vraptor-jpa/commit/42e7ef51e22b36672068aa2e846b89e75e4966d2) was merged into master (that's the vr4 version of this plugin).
and the release is already [available on maven](http://search.maven.org/#artifactdetails%7Cbr.com.caelum.vraptor%7Cvraptor-jpa%7C4.0.3%7Cjar), version 4.0.3. Kind regards

**Comment by rafaelGuerreiro** [comment]
Sorry, I've just seen this. Hehehe, thanks so much!
